### ISSUE TITLE
Publish 2.43.0-1 to npmjs.org

### ISSUE THREAD

**Issue by tobli** [uxebu/webdrvr#2]
Hi,
2.43.0-1 was release on GitHub on Oct 28, 2014. However the latest published version on https://www.npmjs.com/package/webdrvr is 2.43.0-0. It'd be great to have the latest version published.

Thanks!

**Comment by klipstein** [comment]
Thanks for the reminder. I've just published that version: https://www.npmjs.com/package/webdrvr
